// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpKlX8OGmYiYfyuD7yyf34c_vXQZohvoM',
    appId: '1:234486617658:web:8e3ac14ec5ae5f9b80c703',
    messagingSenderId: '234486617658',
    projectId: 'samundar-sathi',
    authDomain: 'samundar-sathi.firebaseapp.com',
    storageBucket: 'samundar-sathi.appspot.com',
    measurementId: 'G-VNYF3HTSZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0D2q7LPlhZHphxKMYWwekTadpNQKGZ9k',
    appId: '1:234486617658:android:5bb997760cdce82980c703',
    messagingSenderId: '234486617658',
    projectId: 'samundar-sathi',
    storageBucket: 'samundar-sathi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOo0IC8SLAt3_Zt2n59hBp180VSqz7qQ',
    appId: '1:234486617658:ios:60b039edd4a2588580c703',
    messagingSenderId: '234486617658',
    projectId: 'samundar-sathi',
    storageBucket: 'samundar-sathi.appspot.com',
    iosBundleId: 'com.example.samundarSaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOo0IC8SLAt3_Zt2n59hBp180VSqz7qQ',
    appId: '1:234486617658:ios:60b039edd4a2588580c703',
    messagingSenderId: '234486617658',
    projectId: 'samundar-sathi',
    storageBucket: 'samundar-sathi.appspot.com',
    iosBundleId: 'com.example.samundarSaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpKlX8OGmYiYfyuD7yyf34c_vXQZohvoM',
    appId: '1:234486617658:web:079659680b12989680c703',
    messagingSenderId: '234486617658',
    projectId: 'samundar-sathi',
    authDomain: 'samundar-sathi.firebaseapp.com',
    storageBucket: 'samundar-sathi.appspot.com',
    measurementId: 'G-N7BPQKW0XZ',
  );
}
